### PR TITLE
Add support for phpunit-coverage-check

### PR DESCRIPTION
**Pull request by ericsizemore**
Add phpunit-coverage-check

### CODE REVIEW

**Comment by theseer** [comment]
Thanks for providing this PR.

The releases look fine and I do not have any technical objections to merging this but a political one.

Your project is a __fork__ of what appears to be an unmaintained original - without any note by the original authors of them not further supporting or developing it. Yet, you wish to claim an alias that would point to your fork.

I'd be more at ease when you'd choose a different name or alias not colliding with the original.

**Comment by ericsizemore** [comment]
I completely understand, and my apologies. I do not want to cause any potential issues. I will reach out to the original author @richardregeer.

Thank you.

**Comment by ericsizemore** [comment]
Hello,

I've had a chance to talk with the author of the original library via email. I understand they have no current plans on making changes to the project, though I cannot assume they have dropped development or support entirely.  So, with that, I have changed the alias I submitted my fork under. If that is still not an acceptable alias/name, please let me know.

Thank you.

**Comment by theseer** [comment]
> I have changed the alias I submitted my fork under. If that is still not an acceptable alias/name, please let me know.

No, this is fine and works for me.
For consistency, I'd suggest maybe you also want to rename your project to match the alias?

**Comment by theseer** [comment]
You can update the URL with a new PR in case you decide to rename your project.

**Comment by ericsizemore** [comment]
> You can update the URL with a new PR in case you decide to rename your project.

Once I have the time to do so, that is the plan. :)

**Pull request merged**
