### PR TITLE
Fix ordering of repositories by alias

### PR DESCRIPTION
**Pull request by Aeliot-Tm**
This commit fixes ordering of repositories to pass automated testing introduced in PR: https://github.com/phar-io/phar.io/pull/160

So, ideally this PRs should be merged together

### CODE REVIEW

**Comment by Aeliot-Tm** [comment]
Hi @theseer,

Could you have a look?

**Comment by theseer** [comment]
Looks okay, but github claims there are conflicts. Please fix those :)

**Comment by Aeliot-Tm** [comment]
Lets me have a look

**Comment by Aeliot-Tm** [comment]
@theseer Done

**Pull request merged**
