### PR TITLE
Adds support for phpbench

### PR DESCRIPTION
**Pull request by dantleech**
:wave:

### CODE REVIEW

**Comment by theseer** [comment]
Merged.

Please note: The file `phpbench.phar.asc` attached to the current release is a gpg public key. While the public key is needed, it has to be provided via keyservers. The attachment needs to be a signature.

**Comment by dantleech** [comment]
hmm, that was wrong then, I guess that's why I get this error:

```
hive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpbench/phpbench/releases
Downloading https://github.com/phpbench/phpbench/releases/download/0.16.4/phpbench.phar
Downloading https://github.com/phpbench/phpbench/releases/download/0.16.4/phpbench.phar.asc
[ERROR]    An error occurred while processing your request:

          Argument 1 passed to PharIo\Phive\GnupgVerificationResult::__construct() must be of the type array, null given, called in phar:///usr/local/bin/phive/src/services/signature/gpg/GnupgSignatureVerifier.php on line 61                              
          
          #0 har:///usr/local/bin/phive/src/services/signature/gpg/GnupgVerificationResult.php(14)
          #1 har:///usr/local/bin/phive/src/services/signature/gpg/GnupgSignatureVerifier.php(61): PharIo\Phive\GnupgVerificationResult->__construct()                                                                                                        
          #2 har:///usr/local/bin/phive/src/services/signature/gpg/GnupgSignatureVerifier.php(38): PharIo\Phive\GnupgSignatureVerifier->attemptVerification()                                                                                                 
          #3 har:///usr/local/bin/phive/src/services/phar/PharDownloader.php(109): PharIo\Phive\GnupgSignatureVerifier->verify()                                                                                                                              
          #4 har:///usr/local/bin/phive/src/services/phar/PharDownloader.php(61): PharIo\Phive\PharDownloader->verifySignature()                                                                                                                              
          #5 har:///usr/local/bin/phive/src/services/phar/PharService.php(38): PharIo\Phive\PharDownloader->download()
          #6 har:///usr/local/bin/phive/src/services/phar/InstallService.php(68): PharIo\Phive\PharService->getPharFromRelease()                                                                                                                              
          #7 har:///usr/local/bin/phive/src/commands/install/InstallCommand.php(63): PharIo\Phive\InstallService->execute()
          #8 har:///usr/local/bin/phive/src/commands/install/InstallCommand.php(51): PharIo\Phive\InstallCommand->installRequestedPhar()                                                                                                                      
          #9 har:///usr/local/bin/phive/src/shared/cli/Runner.php(211): PharIo\Phive\InstallCommand->execute()
          #10 har:///usr/local/bin/phive/src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #11 usr/local/bin/phive(306): PharIo\Phive\Cli\Runner->run()
          #12 {main}

          Environment: PHP 7.3.2-3
          Phive Version: 0.12.1

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
```

I have now removed the wrong `.asc` file, don't know if it's worth reverting this merge until I read the docs and get this working on Travis correctly?

**Comment by dantleech** [comment]
Note I've manually added the GPG signature now and it installs OK. Will need to get it working on travis later.

Thanks :+1:

**Comment by theseer** [comment]
Good job!

Yes, I also discovered `phive` has issues with non-signature `.asc` files. We somehow didn't think of checking whether or not the file is actually a signature ;)

Already noted as bug https://github.com/phar-io/phive/issues/180.

**Pull request merged**
