### PR TITLE
Add twig-cs-fixer phar

### PR DESCRIPTION
**Pull request by VincentLanglet**
I'm introducing phar in my tool https://github.com/VincentLanglet/Twig-CS-Fixer/releases/tag/3.0.0-rc-1

### CODE REVIEW

**Comment by theseer** [comment]
I merged this and deployed the updated repo data file.

To make your phar work with phive though, the public key `DEBB71EDE9601234` uploaded to `keys.openpgp.org` needs to be verified.

**Comment by theseer** [comment]
GPG Keys usually contain one or more UID entries, identifying entities. For privacy reasons, `keys.opengpg.org` is stripping them by default until a confirmation is received.

Assuming you used `https://keys.openpgp.org/upload` to upload it, they will send a confirmation request mail to every UID email listed. This is used as a) proof-of-ownership and b) confirmation to have the respective UID / email be published.

Without a UID though, the key is basically useless: It only proofs *someone* signed it and nobody tampered with it since then. But as we have no idea who that might be, this doesn't really help ;)

**Comment by thePanz** [comment]
I can confirm that manually importing the phar from phive results in an error.

There is an additional warning about somehing with the GPG key missing the "UID"

**Comment by theseer** [comment]
That's exactly the problem I pointed out :)

**Comment by VincentLanglet** [comment]
I sign with the github noreply adress... Didn't know about this.

I'm working on a fix https://github.com/VincentLanglet/Twig-CS-Fixer/pull/299

**Comment by VincentLanglet** [comment]
> I can confirm that manually importing the phar from phive results in an error.
> 
> There is an additional warning about somehing with the GPG key missing the "UID"

Should be better with the new version https://github.com/VincentLanglet/Twig-CS-Fixer/releases/tag/3.0.1 @thePanz

**Comment by thePanz** [comment]
@VincentLanglet I can confirm that running `phive install https://github.com/VincentLanglet/Twig-CS-Fixer/releases/download/3.0.1/twig-cs-fixer.phar` properly handles the GPG key :+1: 

#### Minor information:

I was initially not able to install the phar using the alias `twig-cs-fixer`, as shown below:
```
$ phive install twig-cs-fixer

Phive 0.15.2 - Copyright (C) 2015-2024 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    Could not resolve requested PHAR twig-cs-fixer
```

It required to run `phive update-repository-list` first.

Not sure if such update is automatic or scheduled by phive

**Comment by theseer** [comment]
> Not sure if such update is automatic or scheduled by phive

Phive will keep a downloaded copy - in case one exists - for a max of 7 days before automagically trying to get a new one.

**Pull request merged**
