### PR TITLE
Add PHPStan

### PR DESCRIPTION
**Pull request by ondrejmirtes**
Hi,
I'd like to add PHPStan, a static analyzer that focuses on finding bugs in PHP applications. It's gaining a lot of traction - after publishing it almost a year ago, it gathered more than 2,300 stars on GitHub and around 400k downloads on Packagist already. You can find out more about it in an [introductory article on Medium](https://medium.com/@ondrejmirtes/phpstan-2939cd0ad0e3) and of course [on GitHub](https://github.com/phpstan/phpstan).

### CODE REVIEW

**Comment by theseer** [comment]
Before I push this to production, please ensure that the key used for signing can be found on the GPG keyservers (we use the pools from sks-keyservers.net):

```shell
theseer@nyda ~/storage/php/css2xpath $ phive install phpstan
Phive 0.8.2-2-g9b52a54 - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpstan/phpstan/releases
Downloading https://github.com/phpstan/phpstan/releases/download/0.8.5/phpstan.phar
Downloading https://github.com/phpstan/phpstan/releases/download/0.8.5/phpstan.phar.asc
Downloading key 8E730BA25823D8B5
Trying https://hkps.pool.sks-keyservers.net
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x8E730BA25823D8B5&op=index&options=mr
[WARNING]  Failed with error code 404: Unexpected Response Code 404 while requesting https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x8E730BA25823D8B5&op=index&options=mr 
[ERROR]    PublicKey 8E730BA25823D8B5 not found on key servers 
```

Manual lookup: 
```
http://ha.pool.sks-keyservers.net/pks/lookup?op=vindex&search=8E730BA25823D8B5
```


http://ha.pool.sks-keyservers.net/pks/lookup?op=vindex&search=8E730BA25823D8B5

**Comment by ondrejmirtes** [comment]
I published it to the keyserver, at least I hope (first time I did this) :)

**Comment by theseer** [comment]
Looks good now :)

**Comment by theseer** [comment]
Okay, the hkps pool didn't catch up yet.

I'll publish it anyway, thanks for adding PHPStan and supporting phive.

**Comment by theseer** [comment]
Site updated.

Some servers in the pool already have the key, some don't yet. So, will take some more time for the key to propagate before it will work for everybody.

**Comment by theseer** [comment]
```
theseer@nyda /tmp/xx $ phive install phpstan
Phive 0.8.2-2-g9b52a54 - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpstan/phpstan/releases
Downloading https://github.com/phpstan/phpstan/releases/download/0.8.5/phpstan.phar
Downloading https://github.com/phpstan/phpstan/releases/download/0.8.5/phpstan.phar.asc
Downloading key 8E730BA25823D8B5
Trying https://hkps.pool.sks-keyservers.net
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x8E730BA25823D8B5&op=index&options=mr
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x8E730BA25823D8B5&op=get&options=mr
Successfully downloaded key

	Fingerprint: 19AB 1FB8 9EF5 88C9 6EF0 A00B 8E73 0BA2 5823 D8B5

	Ondrej Mirtes <ondrej@mirtes.cz> (2017-08-15)

	Created: 2017-08-15

Import this key? [y|N] y
Linking /home/theseer/.phive/phars/phpstan.phar to /tmp/xx/tools/phpstan
```

**Comment by ondrejmirtes** [comment]
Thank you 😊

**Pull request merged**
