### PR TITLE
Adds phpdocumentor

### PR DESCRIPTION
**Pull request by jaapio**

### CODE REVIEW

**Comment by theseer** [comment]
Thank you.

Please note: Installing phpDocumentor currently fails:
```
theseer@nyda ~/xx $ phive install phpdocumentor
Phive 0.6.2-31-gfc2f07a-dirty - Copyright (C) 2015-2017 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpdocumentor/phpdocumentor2/releases
Downloading https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar
Downloading https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpdocumentor-2.9.0.asc
Downloading key 86BED3D6EFA8B121
Trying https://hkps.pool.sks-keyservers.net
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x86BED3D6EFA8B121&op=index&options=mr
[WARNING]  Failed with error code 22: The requested URL returned error: 404 Not found (while requesting https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x86BED3D6EFA8B121&op=index&options=mr) 
[ERROR]    PublicKey 86BED3D6EFA8B121 not found on key servers 
```

**Comment by jaapio** [comment]
Thanks for reporting. I will have a look.

Op ma 30 jan. 2017 16:07 schreef Arne Blankerts <notifications@github.com>:

**Comment by jaapio** [comment]
I Added the key to sks-keyservers.net it should be available soon.

**Comment by theseer** [comment]
Works now.

**Pull request merged**
