### PR TITLE
Add PHP CS Fixer

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by theseer** [comment]
The only signed release of php-cs-fixer is 2.2.20, the 2.12 and 2.11 releases are not signed.

Is that intentional?

**Comment by theseer** [comment]
A disregard that, i obviously was too fast ;)

**Comment by keradus** [comment]
no worry, glad to see it merged ;)

**Comment by theseer** [comment]
Thanks for supporting phive! :-)

**Pull request merged**
