### PR TITLE
Add composer-unused/composer-unused

### PR DESCRIPTION
**Pull request by icanhazstring**
Add composer-unused to the list.

### CODE REVIEW

**Comment by theseer** [comment]
I'm not convinced the 0.7.0 phar is build correctly as it simply doesn't do anything when executing it. Is that expected?

**Comment by icanhazstring** [comment]
Strange 🤔 
Let me check again.

**Comment by theseer** [comment]
Doesn't stop me from adding the alias already of course :)

**Comment by theseer** [comment]
```
theseer@nyda /tmp/x8 $ phive install composer-unused
Phive 0.13.2 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/composer-unused/composer-unused/releases
Downloading https://github.com/composer-unused/composer-unused/releases/download/0.7.0/composer-unused.phar
Downloading https://github.com/composer-unused/composer-unused/releases/download/0.7.0/composer-unused.phar.asc
Linking /home/theseer/.phive/phars/composer-unused-0.7.0.phar to /tmp/x8/tools/composer-unused

theseer@nyda /tmp/x8 $ ./tools/composer-unused 
theseer@nyda /tmp/x8 $ ./tools/composer-unused  --version
theseer@nyda /tmp/x8 $ ./tools/composer-unused --help
theseer@nyda /tmp/x8 $ ./tools/composer-unused asfsafd
theseer@nyda /tmp/x8 $
```

That looks strange to me but maybe that's expected ;-)

**Comment by icanhazstring** [comment]
Well thanks for adding 😉
Will check the phar. Maybe there was a problem uploading it while sitting in the train 😅

**Comment by icanhazstring** [comment]
Now its work, thanks again for quick merge :)

**Pull request merged**
