### PR TITLE
Website updates and add Doctum

### PR DESCRIPTION
**Pull request by williamdes**
- Updated Copyright years
- Added [Doctum](https://github.com/code-lts/doctum#readme)
- Fixed http links as much as possible
- Removed an inline style because of `Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash or a nonce is required to enable inline execution.`
- Added a missing robots.txt, thank you Lighthouse !

Closes: #98

### CODE REVIEW

**Comment by williamdes** [comment]
I am finished now @theseer 
Maybe you prefer to wait to be in 2021 ?

**Comment by williamdes** [comment]
Hi @theseer
Did you miss this notification ?

Happy new year !

**Comment by theseer** [comment]
No, I didn't. Thanks for the reminder though.

Let me explain the hold-up:

Your changes include links to external sites where you upgraded them from `http` to `https`. While that is technically a good thing, not all those sites actually work via `https` (yet). 

At least one site is my own, and so before I publish this, I need to fix that. I didn't check all the links though because of a lack of time.

**Comment by williamdes** [comment]
> Your changes include links to external sites where you upgraded them from http to https. While that is technically a good thing, not all those sites actually work via https (yet).

I tested every link before updating the protocol ;)

> At least one site is my own, and so before I publish this, I need to fix that. I didn't check all the links though because of a lack of time.

Let me know if you want me to push another commits when you enabled https


Also one great tool is: https://www.npmjs.com/package/broken-link-checker

**Comment by theseer** [comment]
> > Your changes include links to external sites where you upgraded them from http to https. While that is technically a good thing, not all those sites actually work via https (yet).
> 
> I tested every link before updating the protocol ;)

Funny, when I tested `https://phpdox.net` I got a certificate error. But indeed seems to work now.
Looks good then :+1:

**Pull request merged**
