### PR TITLE
Add Pipelines

### PR DESCRIPTION
**Pull request by ktomk**
Pipelines - Run Bitbucket Pipelines Wherever They Dock - https://github.com/ktomk/pipelines

### CODE REVIEW

**Comment by theseer** [comment]
Thank you for this PR and supporting phive.

Unfortunately, the signature attachment for version 0.0.8 seems to be not a GPG signature. It's a comparatively large binary blurb (50+ kb) but should be an ~550 bytes ascii file. 

Before this is not fixed, users cannot install `pipelines` via phive.
You can actually test your release by using the github name: `phive install ktomk/pipelines`.

**Comment by ktomk** [comment]
Just pushed for release 0.0.9 with a fixed build, 0.0.8 had a GPG signature but not a detached one.

**Comment by ktomk** [comment]
Hi Arne, thanks again for your feedback, was late. Looks good now with your suggest test:

~~~
phive install ktomk/pipelines
Phive 0.9.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/ktomk/pipelines/releases
Downloading https://github.com/ktomk/pipelines/releases/download/0.0.9/pipelines.phar
Downloading https://github.com/ktomk/pipelines/releases/download/0.0.9/pipelines.phar.asc
Linking /home/tom/.phive/phars/pipelines.phar to /home/tom/PhpstormProjects/platform/dist/aws/tools/pipelines
~~~

... those who can properly copy and paste .... :)

**Comment by theseer** [comment]
Merged and published.
Please run `phive update-repository-list` to force an update to the latest version.

**Comment by ktomk** [comment]
@theseer Thanks for all your support!

**Pull request merged**
