### PR TITLE
Ocular & Coveralls

### PR DESCRIPTION
**Pull request by ashnazg**
for #28

### CODE REVIEW

**Comment by theseer** [comment]
Thank you for this pull request.

Unfortunately, neither project is currently providing gpg signed phar releases. For ocular there is not even a phar available via the github releases.

Sorry, but this PR will not be merged. Once they provide GPG signed releases, feel free to reopen this.

**Comment by theseer** [comment]
Minor Correction for coveralls: Version 1.1.0 is the only release with a signature, current version 2.0.0 is not signed.

**Comment by theseer** [comment]
Coveralls has been added successfully.

**Comment by ashnazg** [comment]
I think ocular is now ready -- https://github.com/scrutinizer-ci/ocular/issues/38

**Comment by theseer** [comment]
No update provided. Closing.

Feel free to reopen once signatures are released.

**Pull request closed without merging**
